module.exports = Object.freeze({
    MAIN: 'main-shell',
    DESKTOP: 'desktop-platform',
    NOTES: 'notes',
    NOTE_MINI: 'note-mini',
    MEMO: 'memo',
    FORUM: 'forum',
    LOG: 'log',
    RAG_OBSERVER: 'rag-observer',
    DICE: 'dice',
    CANVAS: 'canvas',
    TRANSLATOR: 'translator',
    MUSIC: 'music',
    THEMES: 'themes',
    TASK: 'task',
    PLUGIN_MANAGER: 'plugin-manager',
});
