/**
 * VCPdesktop - 内置翻译挂件模块
 * 负责：调用 vcpAPI.post() 实现 AI 驱动的多语言翻译
 * 
 * 这是一个官方示范插件，演示如何使用桌面 widget 的 vcpAPI.post() 方法
 * 安全地调用后端 AI API，无需暴露真实的 URL 和 API Key。
 */

'use strict';

(function () {
    const { state, CONSTANTS, widget } = window.VCPDesktop;

    // 翻译挂件 HTML 模板
    var TRANSLATE_HTML = [
        '<style>',
        '.vt-container { padding: 16px; background: linear-gradient(135deg, rgba(20,28,58,0.92), rgba(30,40,70,0.88)); border-radius: 12px; color: #fff; font-family: "Segoe UI", -apple-system, sans-serif; min-width: 320px; backdrop-filter: blur(12px); display: flex; flex-direction: column; gap: 12px; }',
        '.vt-header { display: flex; align-items: center; justify-content: space-between; }',
        '.vt-title { font-size: 15px; font-weight: 600; }',
        '.vt-title-icon { font-size: 18px; margin-right: 6px; }',
        '.vt-model-row { display: flex; align-items: center; gap: 8px; }',
        '.vt-label { font-size: 11px; color: rgba(255,255,255,0.5); flex-shrink: 0; }',
        '.vt-model-input { flex: 1; padding: 5px 8px; background: rgba(255,255,255,0.06); border: 1px solid rgba(255,255,255,0.1); border-radius: 6px; color: #fff; font-size: 11px; outline: none; font-family: monospace; transition: border-color 0.2s; }',
        '.vt-model-input:focus { border-color: rgba(100,180,255,0.4); }',
        '.vt-lang-row { display: flex; align-items: center; gap: 8px; }',
        '.vt-lang-select { flex: 1; padding: 6px 8px; background: rgba(255,255,255,0.06); border: 1px solid rgba(255,255,255,0.1); border-radius: 6px; color: #fff; font-size: 12px; outline: none; cursor: pointer; appearance: none; -webkit-appearance: none; background-image: url("data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' viewBox=\'0 0 10 6\'%3E%3Cpath d=\'M0 0l5 6 5-6z\' fill=\'rgba(255,255,255,0.4)\'/%3E%3C/svg%3E"); background-repeat: no-repeat; background-position: right 8px center; background-size: 8px; padding-right: 22px; transition: border-color 0.2s; }',
        '.vt-lang-select:focus { border-color: rgba(100,180,255,0.4); }',
        '.vt-lang-select option { background: #1a1a2e; color: #fff; }',
        '.vt-swap-btn { width: 28px; height: 28px; border-radius: 50%; border: 1px solid rgba(255,255,255,0.1); background: rgba(255,255,255,0.06); color: rgba(255,255,255,0.6); font-size: 14px; cursor: pointer; display: flex; align-items: center; justify-content: center; flex-shrink: 0; transition: all 0.15s; }',
        '.vt-swap-btn:hover { background: rgba(255,255,255,0.12); color: rgba(255,255,255,0.9); transform: rotate(180deg); }',
        '.vt-input-area { position: relative; }',
        '.vt-textarea { width: 100%; min-height: 80px; max-height: 160px; padding: 10px; background: rgba(255,255,255,0.04); border: 1px solid rgba(255,255,255,0.08); border-radius: 8px; color: #fff; font-size: 13px; line-height: 1.5; outline: none; resize: vertical; font-family: inherit; transition: border-color 0.2s; }',
        '.vt-textarea:focus { border-color: rgba(100,180,255,0.4); }',
        '.vt-textarea::placeholder { color: rgba(255,255,255,0.25); }',
        '.vt-char-count { position: absolute; bottom: 6px; right: 8px; font-size: 10px; color: rgba(255,255,255,0.25); }',
        '.vt-actions { display: flex; align-items: center; gap: 8px; }',
        '.vt-translate-btn { flex: 1; padding: 8px 16px; background: linear-gradient(135deg, rgba(60,120,255,0.6), rgba(80,100,220,0.5)); border: 1px solid rgba(100,150,255,0.3); border-radius: 8px; color: #fff; font-size: 13px; font-weight: 500; cursor: pointer; transition: all 0.2s; text-align: center; }',
        '.vt-translate-btn:hover { background: linear-gradient(135deg, rgba(60,120,255,0.8), rgba(80,100,220,0.7)); }',
        '.vt-translate-btn:active { transform: scale(0.98); }',
        '.vt-translate-btn.loading { opacity: 0.6; cursor: wait; }',
        '.vt-translate-btn.loading::after { content: ""; display: inline-block; width: 12px; height: 12px; border: 2px solid rgba(255,255,255,0.3); border-top-color: #fff; border-radius: 50%; animation: vt-spin 0.8s linear infinite; margin-left: 8px; vertical-align: middle; }',
        '@keyframes vt-spin { to { transform: rotate(360deg); } }',
        '.vt-clear-btn { padding: 8px 12px; background: rgba(255,255,255,0.06); border: 1px solid rgba(255,255,255,0.08); border-radius: 8px; color: rgba(255,255,255,0.5); font-size: 12px; cursor: pointer; transition: all 0.15s; flex-shrink: 0; }',
        '.vt-clear-btn:hover { background: rgba(255,255,255,0.1); color: rgba(255,255,255,0.8); }',
        '.vt-output-area { min-height: 60px; padding: 10px; background: rgba(255,255,255,0.04); border: 1px solid rgba(255,255,255,0.08); border-radius: 8px; font-size: 13px; line-height: 1.6; color: rgba(255,255,255,0.9); white-space: pre-wrap; word-break: break-word; position: relative; display: none; }',
        '.vt-output-area.visible { display: block; }',
        '.vt-output-placeholder { color: rgba(255,255,255,0.2); font-style: italic; }',
        '.vt-copy-btn { position: absolute; top: 6px; right: 6px; padding: 3px 8px; background: rgba(255,255,255,0.08); border: 1px solid rgba(255,255,255,0.1); border-radius: 4px; color: rgba(255,255,255,0.5); font-size: 10px; cursor: pointer; transition: all 0.15s; }',
        '.vt-copy-btn:hover { background: rgba(255,255,255,0.15); color: rgba(255,255,255,0.9); }',
        '.vt-copy-btn.copied { color: rgba(100,220,100,0.9); }',
        '.vt-error { padding: 8px 10px; background: rgba(255,80,80,0.1); border: 1px solid rgba(255,80,80,0.2); border-radius: 6px; color: rgba(255,120,120,0.9); font-size: 11px; display: none; }',
        '.vt-error.visible { display: block; }',
        '.vt-footer { display: flex; align-items: center; justify-content: space-between; font-size: 10px; color: rgba(255,255,255,0.25); }',
        '.vt-shortcut { opacity: 0.5; }',
        '</style>',
        '<div class="vt-container">',
        '    <div class="vt-header">',
        '        <span><span class="vt-title-icon">🌐</span><span class="vt-title">AI 翻译</span></span>',
        '    </div>',
        '',
        '    <div class="vt-model-row">',
        '        <span class="vt-label">模型</span>',
        '        <input class="vt-model-input" id="vt-model" type="text" value="gemini-3-flash-preview" placeholder="输入模型名称..." />',
        '    </div>',
        '',
        '    <div class="vt-lang-row">',
        '        <select class="vt-lang-select" id="vt-source-lang">',
        '            <option value="auto" selected>自动检测</option>',
        '            <option value="中文">中文</option>',
        '            <option value="English">English</option>',
        '            <option value="日本語">日本語</option>',
        '            <option value="한국어">한국어</option>',
        '            <option value="Français">Français</option>',
        '            <option value="Deutsch">Deutsch</option>',
        '            <option value="Español">Español</option>',
        '            <option value="Русский">Русский</option>',
        '            <option value="Português">Português</option>',
        '            <option value="Italiano">Italiano</option>',
        '            <option value="العربية">العربية</option>',
        '            <option value="ไทย">ไทย</option>',
        '            <option value="Tiếng Việt">Tiếng Việt</option>',
        '        </select>',
        '        <button class="vt-swap-btn" id="vt-swap" title="交换语言">⇄</button>',
        '        <select class="vt-lang-select" id="vt-target-lang">',
        '            <option value="中文">中文</option>',
        '            <option value="English" selected>English</option>',
        '            <option value="日本語">日本語</option>',
        '            <option value="한국어">한국어</option>',
        '            <option value="Français">Français</option>',
        '            <option value="Deutsch">Deutsch</option>',
        '            <option value="Español">Español</option>',
        '            <option value="Русский">Русский</option>',
        '            <option value="Português">Português</option>',
        '            <option value="Italiano">Italiano</option>',
        '            <option value="العربية">العربية</option>',
        '            <option value="ไทย">ไทย</option>',
        '            <option value="Tiếng Việt">Tiếng Việt</option>',
        '        </select>',
        '    </div>',
        '',
        '    <div class="vt-input-area">',
        '        <textarea class="vt-textarea" id="vt-input" placeholder="输入要翻译的文本..." maxlength="5000"></textarea>',
        '        <span class="vt-char-count" id="vt-char-count">0 / 5000</span>',
        '    </div>',
        '',
        '    <div class="vt-actions">',
        '        <button class="vt-translate-btn" id="vt-translate-btn">翻译</button>',
        '        <button class="vt-clear-btn" id="vt-clear-btn">清空</button>',
        '    </div>',
        '',
        '    <div class="vt-error" id="vt-error"></div>',
        '',
        '    <div class="vt-output-area" id="vt-output">',
        '        <button class="vt-copy-btn" id="vt-copy-btn">复制</button>',
        '        <div id="vt-output-text"></div>',
        '    </div>',
        '',
        '    <div class="vt-footer">',
        '        <span>通过 vcpAPI.post() 调用</span>',
        '        <span class="vt-shortcut">Ctrl+Enter 翻译</span>',
        '    </div>',
        '</div>',
        '<script>',
        '(function() {',
        '    var inputEl = document.getElementById("vt-input");',
        '    var outputEl = document.getElementById("vt-output");',
        '    var outputTextEl = document.getElementById("vt-output-text");',
        '    var errorEl = document.getElementById("vt-error");',
        '    var translateBtn = document.getElementById("vt-translate-btn");',
        '    var clearBtn = document.getElementById("vt-clear-btn");',
        '    var copyBtn = document.getElementById("vt-copy-btn");',
        '    var swapBtn = document.getElementById("vt-swap");',
        '    var modelInput = document.getElementById("vt-model");',
        '    var sourceLang = document.getElementById("vt-source-lang");',
        '    var targetLang = document.getElementById("vt-target-lang");',
        '    var charCount = document.getElementById("vt-char-count");',
        '    var isLoading = false;',
        '',
        '    // 字符计数',
        '    inputEl.addEventListener("input", function() {',
        '        charCount.textContent = inputEl.value.length + " / 5000";',
        '    });',
        '',
        '    // 交换语言',
        '    swapBtn.addEventListener("click", function() {',
        '        if (sourceLang.value === "auto") {',
        '            // 自动检测模式下，将目标语言设为源语言，目标语言设为中文',
        '            sourceLang.value = targetLang.value;',
        '            targetLang.value = "中文";',
        '        } else {',
        '            var tmp = sourceLang.value;',
        '            sourceLang.value = targetLang.value;',
        '            targetLang.value = tmp;',
        '        }',
        '        // 如果有翻译结果，交换输入输出',
        '        if (outputEl.classList.contains("visible") && outputTextEl.textContent) {',
        '            var translated = outputTextEl.textContent;',
        '            inputEl.value = translated;',
        '            charCount.textContent = translated.length + " / 5000";',
        '            outputEl.classList.remove("visible");',
        '        }',
        '    });',
        '',
        '    // 清空',
        '    clearBtn.addEventListener("click", function() {',
        '        inputEl.value = "";',
        '        charCount.textContent = "0 / 5000";',
        '        outputEl.classList.remove("visible");',
        '        outputTextEl.textContent = "";',
        '        errorEl.classList.remove("visible");',
        '        inputEl.focus();',
        '    });',
        '',
        '    // 复制结果',
        '    copyBtn.addEventListener("click", function() {',
        '        var text = outputTextEl.textContent;',
        '        if (!text) return;',
        '        try {',
        '            navigator.clipboard.writeText(text).then(function() {',
        '                copyBtn.textContent = "已复制!";',
        '                copyBtn.classList.add("copied");',
        '                setTimeout(function() {',
        '                    copyBtn.textContent = "复制";',
        '                    copyBtn.classList.remove("copied");',
        '                }, 1500);',
        '            });',
        '        } catch(e) {',
        '            // 回退方案',
        '            var textarea = document.createElement("textarea");',
        '            textarea.value = text;',
        '            textarea.style.position = "fixed";',
        '            textarea.style.opacity = "0";',
        '            root.appendChild(textarea);',
        '            textarea.select();',
        '            try { _realDoc.execCommand("copy"); } catch(ex) {}',
        '            root.removeChild(textarea);',
        '            copyBtn.textContent = "已复制!";',
        '            copyBtn.classList.add("copied");',
        '            setTimeout(function() {',
        '                copyBtn.textContent = "复制";',
        '                copyBtn.classList.remove("copied");',
        '            }, 1500);',
        '        }',
        '    });',
        '',
        '    // 翻译核心',
        '    async function doTranslate() {',
        '        var text = inputEl.value.trim();',
        '        if (!text) {',
        '            inputEl.focus();',
        '            return;',
        '        }',
        '        if (isLoading) return;',
        '',
        '        isLoading = true;',
        '        translateBtn.classList.add("loading");',
        '        translateBtn.textContent = "翻译中";',
        '        errorEl.classList.remove("visible");',
        '        outputEl.classList.remove("visible");',
        '',
        '        var src = sourceLang.value;',
        '        var tgt = targetLang.value;',
        '        var model = modelInput.value.trim() || "gemini-2.5-flash-preview";',
        '',
        '        // 构建翻译 prompt',
        '        var systemPrompt = "你是一个专业的翻译引擎。用户会给你一段文本，你需要将其翻译为目标语言。请只输出翻译结果，不要输出任何解释、注释或额外内容。保持原文的格式和段落结构。";',
        '',
        '        var userPrompt = "";',
        '        if (src === "auto") {',
        '            userPrompt = "请将以下文本翻译为" + tgt + "：\\n\\n" + text;',
        '        } else {',
        '            userPrompt = "请将以下" + src + "文本翻译为" + tgt + "：\\n\\n" + text;',
        '        }',
        '',
        '        var messages = [',
        '            { role: "system", content: systemPrompt },',
        '            { role: "user", content: userPrompt }',
        '        ];',
        '',
        '        try {',
        '            var result = await vcpAPI.post(messages, {',
        '                model: model,',
        '                temperature: 0.3,',
        '            });',
        '',
        '            if (result.success && result.content) {',
        '                outputTextEl.textContent = result.content;',
        '                outputEl.classList.add("visible");',
        '            } else {',
        '                errorEl.textContent = "❌ 翻译失败: " + (result.error || "未知错误");',
        '                errorEl.classList.add("visible");',
        '            }',
        '        } catch(e) {',
        '            errorEl.textContent = "❌ 请求异常: " + e.message;',
        '            errorEl.classList.add("visible");',
        '            console.error("[TranslateWidget]", e);',
        '        } finally {',
        '            isLoading = false;',
        '            translateBtn.classList.remove("loading");',
        '            translateBtn.textContent = "翻译";',
        '        }',
        '    }',
        '',
        '    // 按钮点击翻译',
        '    translateBtn.addEventListener("click", doTranslate);',
        '',
        '    // Ctrl+Enter 快捷键',
        '    inputEl.addEventListener("keydown", function(e) {',
        '        if (e.key === "Enter" && (e.ctrlKey || e.metaKey)) {',
        '            e.preventDefault();',
        '            doTranslate();',
        '        }',
        '    });',
        '',
        '})();',
        '<\/script>'
    ].join('\n');

    /**
     * 生成翻译挂件
     */
    async function spawnTranslateWidget() {
        var widgetId = 'builtin-translate';

        // 如果已存在则不重复创建
        if (state.widgets.has(widgetId)) return;

        var widgetData = widget.create(widgetId, {
            x: 200,
            y: CONSTANTS.TITLE_BAR_HEIGHT + 40,
            width: 380,
            height: 520,
        });

        widgetData.contentBuffer = TRANSLATE_HTML;
        widgetData.contentContainer.innerHTML = TRANSLATE_HTML;
        widget.processInlineStyles(widgetData);
        widgetData.isConstructing = false;
        widgetData.element.classList.remove('constructing');
        widget.autoResize(widgetData);

        // 延迟执行脚本
        setTimeout(function () {
            widget.processInlineScripts(widgetData);
        }, 100);

        console.log('[VCPdesktop] Translate widget spawned.');
    }

    // ============================================================
    // 导出
    // ============================================================
    window.VCPDesktop = window.VCPDesktop || {};
    window.VCPDesktop.builtinTranslate = {
        spawn: spawnTranslateWidget,
    };

})();